name: ai-image-detector
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - jupyter
  - tqdm
  - numpy
  - scipy
  - matplotlib
  - pandas
  - requests
  - fastapi
  - uvicorn
  - python-multipart
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch
      - torchvision
      - torchsummary
      - transformers
      - diffusers
      - grad-cam