name: ai-image-detector
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - jupyter
  - tqdm
  - numpy
  - scipy
  - matplotlib
  - pandas
  - requests
  - pytorch
  - torchvision
  - fastapi
  - uvicorn
  - python-multipart
  - pip
  - pip:
    - torchsummary
    - transformers
    - diffusers
    - grad-cam
