dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - jupyter
  - numpy
  - matplotlib
  - requests
  - scipy
  - pytorch
  - torchvision
  - fastapi
  - uvicorn
  - python-multipart
  - pip
  - pip:
    - torchsummary
    - transformers
    - diffusers